package org.b612foundation.adam.datamodel.estimation;

public class OorbEstimateConfigurationFactory {
    public static final String OORB_EXECUTOR = "OpenOrb";

    public static OrbitDeterminationConfiguration buildDefaultConfig() {
        var config = OrbitDeterminationConfiguration.builder()
                .executor(OORB_EXECUTOR)
                .executionSetting("verbose.info","1")
                .executionSetting("verbose.error","1")
                .executionSetting("planetary_ephemeris_fname","de430.dat")
                .executionSetting("element_type_out", "cartesian")
                .executionSetting("write.residuals", "F")
                .executionSetting("plot.results","F")
                .executionSetting("plot.open","F")
                .executionSetting("observation.format.out", "des")
                .executionSetting("orbit.format.out", "orb")
                .executionSetting("element_type_comp", "cartesian")
                .executionSetting("integrator", "bulirsch-stoer")
                .executionSetting("integration_step", "1.0")
                .executionSetting("relativity", "T")
                .executionSetting("dynamical_model_init", "n-body")
                .executionSetting("integrator_init", "bulirsch-stoer")
                .executionSetting("integration_step_init", "1.0")
                .executionSetting("simint", "1")
                .measurementSetting("stdev.ra", "1.0")
                .measurementSetting("stdev.dec","1.0")
                .measurementSetting("outlier_rejection", "T")
                .measurementSetting("outlier.multiplier","4.0")
                .measurementSetting("generation.multiplier", "4.0")
                .measurementSetting("generation.gaussian_deviates", "F")
                .measurementSetting("accwin.multiplier", "4.0")
                .measurementSetting("dchi2_rejection", "T")
                .measurementSetting("dchi2.max", "30")
                .measurementSetting("reg.pdf", "F")
                .measurementSetting("obs.mask", "F")
                .measurementSetting("chi2_min.init", "-1")
                .executionSetting("apriori.a.min", "0.00465424")
                .executionSetting("apriori.a.max", "1000")
                .executionSetting("sor.two_point_method", "continued fraction")
                .executionSetting("sor.type", "2")
                .executionSetting("sor.norb", "2000")
                .executionSetting("sor.ntrial", "1000000")
                .executionSetting("sor.two_point_method_sw", "continued fraction")
                .executionSetting("sor.norb.sw", "500")
                .executionSetting("sor.ntrial.sw", "200000")
                .executionSetting("sor.niter", "3")
                .executionSetting("sor.rho11.init", "0.0")
                .executionSetting("sor.rho12.init", "100.0")
                .executionSetting("sor.genwin.offset", "0.0 0.0 0.0 0.0")
                .executionSetting("sor.iterate_bounds", "T T T T")
                .executionSetting("vov.type", "2")
                .executionSetting("vov.norb", "1000")
                .executionSetting("vov.ntrial", "1000000")
                .executionSetting("vov.norb_iter", "1000")
                .executionSetting("vov.ntrial_iter", "1000000")
                .executionSetting("vov.niter", "5")
                .executionSetting("vov.mapping_mask", "T F F F F F")
                .executionSetting("vov.nmap", "101")
                .executionSetting("vov.scaling.lo", "5.0 5.0 5.0 2.0 2.0 2.0")
                .executionSetting("vov.scaling.hi", "5.0 5.0 5.0 2.0 2.0 2.0")
                .executionSetting("vomcmc.type", "1")
                .executionSetting("vomcmc.norb", "200")
                .executionSetting("vomcmc.ntrial", "1000000")
                .executionSetting("vomcmc.norb_iter", "1000")
                .executionSetting("vomcmc.ntrial_iter", "1000000")
                .executionSetting("vomcmc.niter", "5")
                .executionSetting("vomcmc.mapping_mask", "T F F F F F")
                .executionSetting("vomcmc.nmap", "10")
                .executionSetting("vomcmc.scaling.lo", "2.0 2.0 2.0 2.0 2.0 2.0")
                .executionSetting("vomcmc.scaling.hi", "2.0 2.0 2.0 2.0 2.0 2.0")
                .executionSetting("ls.correction_factor", "0.2")
                .executionSetting("ls.rchi2.acceptable", "1.2")
                .executionSetting("ls.niter_major.max", "20")
                .executionSetting("ls.niter_major.min", "2")
                .executionSetting("ls.niter_minor", "100")
                .executionSetting("ls.element_mask", "T T T T T T")
                .executionSetting("cos.gaussian", "F")
                .executionSetting("cos.nsigma", "8")
                .executionSetting("cos.norb", "100")
                .executionSetting("cos.ntrial", "1000")
                .executionSetting("smplx.tol", "1.05")
                .executionSetting("smplx.niter", "1000")
                .executionSetting("smplx.force", "F")
                .executionSetting("smplx.similarity.tol", "0.001")
                .executionSetting("os.norb", "200")
                .executionSetting("os.ntrial", "10000")
                .executionSetting("os.sampling_type", "1")
                .executionSetting("pp.H_estimation", "T")
                .executionSetting("pp.G", "0.15")
                .executionSetting("pp.G_unc", "0.10")
                .build();

        return config;
    }
}
