name: Publish Package

on:
  push:
    branches:
      - develop

env:
  ADAM_STK_LICENSE_DATA: ${{ secrets.ADAM_STK_LICENSE_DATA }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF

      - name: Publish package
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_REF: ${{ secrets.PRIVATE_REPO_USER }}
          GITHUB_TOKEN_REF: ${{ secrets.CICD_PRIVATE_REPO_ACCESS_TOKEN }}
